### ISSUE TITLE
403 Error: 020204

### ISSUE THREAD

**Issue by Casuallynoted** [csdozier/device-concord4#14]
Getting an issue here but I’m not sure what I’ve done wrong. I replaced my Superbus thinking that was the culprit but now I don’t believe it is. The cable is also brand new:

```
Concord 4 Automation Server v2.0
2020-01-27 18:44:05,749 [concordsvr.py:start_logger()] - INFO - Logging started [LEVEL: INFO]…
2020-01-27 18:44:05,757 [concordsvr.py:updateStateOnServer()] - INFO - Panel Information: panelState: connecting
2020-01-27 18:44:05,758 [concordsvr.py:refreshPanelState()] - INFO - Querying panel for state (Concord 4 panel device startup)
2020-01-27 18:44:05,758 [concordsvr.py:updateStateOnServer()] - INFO - Panel Information: state: exploring
2020-01-27 18:44:05,775 [concordsvr.py:logger()] - INFO - Listening for HTTP(S) connections on port: 8066
2020-01-27 18:44:06,262 [concordsvr.py:logger()] - INFO - TX -> https://graph-na04-useast2.api.smartthings.com/api/smartapps/installations/[censoredthenumbershere]/concord/[censoredthenumbershere]/armstatus/disarmed
2020-01-27 18:44:06,264 [concordsvr.py:logger()] - INFO - ST TX Failed: 403 url:armstatus/disarmed
2020-01-27 18:44:06,286 [concord.py:send_message()] - WARNING - Resending message, attempt 2: ‘020204’
2020-01-27 18:44:07,796 [concordsvr.py:updateStateOnServer()] - INFO - Panel Information: state: active
2020-01-27 18:44:10,318 [concordsvr.py:panelMessageHandler()] - INFO - Learning new partition 1 from TOUCHPAD message
2020-01-27 18:44:10,824 [concordsvr.py:panelMessageHandler()] - INFO - Learning new partition 2 from TOUCHPAD message
2020-01-27 18:44:13,871 [concordsvr.py:panelMessageHandler()] - INFO - Learning new partition 3 from TOUCHPAD message
2020-01-27 18:44:14,395 [concordsvr.py:panelMessageHandler()] - INFO - Learning new partition 4 from TOUCHPAD message
2020-01-27 18:44:14,902 [concordsvr.py:panelMessageHandler()] - INFO - Learning new partition 5 from TOUCHPAD message
2020-01-27 18:44:15,408 [concordsvr.py:panelMessageHandler()] - INFO - Learning new partition 6 from TOUCHPAD message
```

and it just sorta repeats from there with 403 errors.

**Comment by csdozier** [comment]
So the issue is not with the superbus module side, its an issue with the
program talking with smarthings

2020-01-27 18:44:06,262 [concordsvr.py:logger()] - INFO - TX ->
https://graph-na04-useast2.api.smartthings.com/api/smartapps/installations/[censoredthenumbershere]/concord/[censoredthenumbershere]/armstatus/disarmed

You need to check your oauth settings.

**Comment by Casuallynoted** [comment]
I'm running through the code generation process but it's given me a hassle every single time. I've gotten the auth code via the simulator but now that I'm trying to run the curl command to get the API Token, it just always gives me the code for a 500 internal server error.

Error
500: Internal Server Error
URI
/oauth/token
Reference Id
300fefa4-f360-497d-8480-3cd7d76ce714
Date
Thu Mar 12 20:26:10 UTC 2020

If there's any other way to do this in a way that ensures I'm doing it right, or some kind of script to generate the url and make it easier I'd love to do that. The last several times I've tried this, I wind up getting a result seemingly at random.

**Comment by Casuallynoted** [comment]
According to Samsung SmartThings Dev support, the code needs to be updated to SmartThings (non-classic) in order to work properly. That could be total misinformation but I thought I should pass it on. This is their response when I asked about the issue:

“ Unfortunately, the project that you've shared with us hasn't been updated to the current documentation. If you're the owner of this project, I suggest you implement the proper update, otherwise, you can request these changes directly to the project's GitHub.”

**Comment by Casuallynoted** [comment]
One possible solution (or idea in general) is to have a local alternative like Hubitat or Homebridge.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by csdozier** [comment]
> I'm running through the code generation process but it's given me a hassle every single time. I've gotten the auth code via the simulator but now that I'm trying to run the curl command to get the API Token, it just always gives me the code for a 500 internal server error.
> 
> Error
> 500: Internal Server Error
> URI
> /oauth/token
> Reference Id
> 300fefa4-f360-497d-8480-3cd7d76ce714
> Date
> Thu Mar 12 20:26:10 UTC 2020
> 
> If there's any other way to do this in a way that ensures I'm doing it right, or some kind of script to generate the url and make it easier I'd love to do that. The last several times I've tried this, I wind up getting a result seemingly at random.

I have not run through the steps in a long time.  I'm waiting to revamp this whole project into the new smart things app when it seems there is good porting documentation. 

I tested the code generation process and it still seems to work.. 

1. In chrome incognito construct a url like below, where you put in your client-id from smart app: 
https://graph.api.smartthings.com/oauth/authorize?response_type=code&client_id=caed733c-xxxx-xxx-xxx-xxxxxxxxxxx&scope=app&redirect_uri=https%3A%2F%2Fgraph-xx.api.smartthings.com%2Foauth%2Fcallback

you will be presented with a page like this:

![image](https://user-images.githubusercontent.com/13787127/77354667-96cf4f00-6d19-11ea-8610-2da7d0dea95a.png)


You check the zones and click authorize.

You get to another page with 404 error, but the code is in the url box (mine starts with rv)


![image](https://user-images.githubusercontent.com/13787127/77354790-c1b9a300-6d19-11ea-9310-ed745cbbaca9.png)

**Comment by Casuallynoted** [comment]
See, I can generate that code fine, but it's the second code retrieval process using curl that's been giving me problems. I'll see if I can get it working using this method for code retrieval though.

**Comment by Casuallynoted** [comment]
It wants me to sign in with a samsung account every time I do it, is that expected behavior?

**Comment by Casuallynoted** [comment]
Here's what the curl command output gives me, when I get the code in the previouio step by signing into samsung smartthings:

`<!doctype html>




 <html lang="en" class="no-js">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="_csrf" content="9b2e8c7a-14d2-4f69-87a4-39584f7f5a07"/>
	
	<meta name="_csrf_header" content="X-CSRF-TOKEN"/>
	<title>Something Went Wrong</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<link rel="shortcut icon" type="image/x-icon" href="/assets/components/common/favicon-4993383b83174ec4d5a7b26bcc8df5b8.ico"/>
	<link rel="apple-touch-icon" href="/assets/components/common/apple-touch-icon-b7275dbac7a4078e4f44859751581016.png"/>
	<link rel="apple-touch-icon" sizes="114x114" href="/assets/components/common/apple-touch-icon-retina-35ea8b3c6aa433fa74ebc97d0b5a2a53.png"/>

	
		<link rel="stylesheet" href="/assets/base/bootstrap-framework-ca068de267e66f972264227b95ad8cb1.css"/>
	

	<link rel="stylesheet" href="/assets/base/common-77e2fb036db019b4c759f2bb145e94d3.css"/>

	
		<script src="/assets/libs/underscore/underscore-6e1f1c149dc88c708f9bfce4a061187f.js" type="text/javascript" ></script>
	

	

	<script src="/assets/apps/main/main-app-5811442e0bc96e2d7374677668e7edc4.js" type="text/javascript" ></script>

	
		<script src="/assets/libs/bootstrap/bootstrap-e3bccdc29cf6e1d0f3e7bc54ccf086ef.js" type="text/javascript" ></script>
	

	
	
		<script type="text/javascript">
			window.heap=window.heap||[],heap.load=function(t,e){window.heap.appid=t,window.heap.config=e;var a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=("https:"===document.location.protocol?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+t+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(t){return function(){heap.push([t].concat(Array.prototype.slice.call(arguments,0)))}},p=["clearEventProperties","identify","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
			heap.load("2894297474");
		</script>
	
	
		<meta name="layout" content="bootstrap-fixed">
		
		<link rel="stylesheet" href="/assets/components/errors/errors-9c6c2a11a83fd2e9a06d49628a0eab12.css"/>
	
</head>
<body class="production-env">

<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-M4C995"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script type="application/javascript">
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-M4C995');
</script>




	<header class="header-main minimized">

	
		<div class="login-tab">
			<div class="login-tab-welcome">
				<div class="st-arrow-container">
					<div class="st-arrow-dropdown"></div>
				</div>
				
				
					
					
						Welcome back, <strong class="username"><a href="/user/show"></a></strong>
					
				
			</div>
			<ul>
				
	



				
					

					
					

					

					
					

					<li><a href="/logout/index">Logout</a></li>
				

			</ul>
		</div>
	
	
	
		<div>
			<div class="gradient-top-bar"></div>
			<div class="clearfix">
				<div id="topNavigation" style="display:none;">
					<div class="mobile-menu-brand"><img src='/assets/components/common/smartthings-logo.png' alt='logo' /></div>
					
						<div class="mobile-menu-icon"><div><div></div></div></div>
					
				</div>
			</div>
		</div>
</header>

	<div class="mobile-menu">
	<ul class="ul-reset">
		
			<li><a href="/user/show">Logged in as: </a></li>
			<li><a href="/logout/index">Logout</a></li>
		
		
		<li><a href="https://shop.smartthings.com">Shop</a></li>
		<li><a href="http://smartthings.com">Learn More</a></li>
		<li><a href="http://smartthings.com/build">Build</a></li>
		<li><a href="http://support.smartthings.com">Support</a></li>
		
			<ul class="logged-in-menu ul-reset">
				<li class="menu-title">Developer Tools:</li>
				
	



				<li class=""><a href="/location/list"><span class="hidden-sm hidden-xs">My </span>Locations</a></li>
				<li class=""><a href="/hub/list"><span class="hidden-sm hidden-xs">My </span>Hubs</a></li>
				<li class=""><a href="/device/list"><span class="hidden-sm hidden-xs">My </span>Devices</a></li>
				
				
				<li class=""><a href="http://docs.smartthings.com/" target="_newWindow">Documentation</a></li>
			</ul>
		
	</ul>
</div>

	
		
	<div class="navbar navbar-default main">
		<div class="container-fluid">
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav main">
					
						<li class=""><a href="/location/list"><span class="hidden-sm hidden-xs">My </span>Locations</a></li>
						<li class=""><a href="/hub/list"><span class="hidden-sm hidden-xs">My </span>Hubs</a></li>
						<li class=""><a href="/device/list"><span class="hidden-sm hidden-xs">My </span>Devices</a></li>
						
						<li class=""><a href="http://docs.smartthings.com/" target="_newWindow">Documentation</a></li>
					
				</ul>
			</div>
		</div>
	</div>


	


<script id="success-template" type="text/x-handlebars-template">
	<div class="inner-wrap">
		<div class="alert alert-success alert-dismissible flash">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			{{message}}
		</div>
	</div>
</script>

<script type="application/javascript">
	function _resize_window_delayed() {
		setTimeout(function() {
			window.dispatchEvent(new Event('resize'));
		}, 50)
	}
</script>

<div id="flash-message-container" class="row">




</div>


		<div class="content">
			<h1>Oh No! Something Went Wrong!</h1>

			
			<dl class="error-details">
				<dt>Error</dt><dd>500: Internal Server Error</dd>
				<dt>URI</dt><dd>/oauth/token</dd>
				<dt>Reference Id</dt><dd>bcb3caef-b2c5-4a69-abaf-f258c0544bef</dd>
				<dt>Date</dt><dd>Wed Apr 01 16:35:36 UTC 2020</dd>
			</dl>
		</div>
	
<div class="inner-wrap clearfix"></div>
<div class="footer main" role="contentinfo">
	<div class="inner-wrap clearfix">
		<div class="pull-left">
			&copy; 2020 SmartThings, Inc. All rights reserved.
		</div>
		
		
			<ul class="pull-right footer-links">
				<li><a href="http://www.smartthings.com/benefits/" target="_blank">Benefits</a></li>
				<li>&nbsp;&nbsp;|&nbsp;&nbsp;</li>
				<li><a href="https://shop.smartthings.com" target="_blank">Shop</a></li>
				<li>&nbsp;&nbsp;|&nbsp;&nbsp;</li>
				<li><a href="http://blog.smartthings.com/" target="_blank">Blog</a></li>
				<li>&nbsp;&nbsp;|&nbsp;&nbsp;</li>
				<li><a href="https://developers.smartthings.com/" target="_blank">Developers</a></li>
				<li>&nbsp;&nbsp;|&nbsp;&nbsp;</li>
				<li><a href="http://support.smartthings.com" target="_blank">Support</a></li>
				<li>&nbsp;&nbsp;|&nbsp;&nbsp;</li>
				<li><a href="http://www.smartthings.com/terms/" target="_blank">Terms of Use</a></li>
				<li>&nbsp;&nbsp;|&nbsp;&nbsp;</li>
				<li><a href="http://www.smartthings.com/privacy/" target="_blank">Privacy Policy</a></li>
			</ul>
		
	</div>
</div>


</body>
</html>
`

**Comment by Casuallynoted** [comment]
Giving it another stab today, went through the entire setup process and every step went by without any need for reattempts. However the output I'm getting here seems to be different:

2020-05-31 21:27:05,784 [concordsvr.py:updateStateOnServer()] - INFO - Panel Information: state: exploring
error: uncaptured python exception, closing channel <__main__.ConcordHTTPServer listening :8066 at 0x75d0c850> (<type 'exceptions.TypeError'>:'NoneType' object is not iterable [/usr/lib/python2.7/asyncore.py|read|83] [/usr/lib/python2.7/asyncore.py|handle_read_event|443] [concordsvr.py|handle_accept|879])
2020-05-31 21:27:05,816 [concordsvr.py:logger()] - INFO - Listening for HTTP(S) connections on port: 8066
2020-05-31 21:27:07,892 [concordsvr.py:logger()] - INFO - TX -> https://graph-na04-useast2.api.smartthings.com/api/smartapps/installations/76feaea9-73a8-4473-973a-d49dd02525ef/concord/35271bd9-8a71-4a45-a350-2cf372074112/armstatus/disarmed
2020-05-31 21:27:07,937 [concordsvr.py:logger()] - INFO - ST TX Failed: 403 url:armstatus/disarmed
2020-05-31 21:27:07,977 [concord.py:message_loop()] - ERROR - BadEncoding("Invalid message encoding: ['0', '3', '2', '2', '\\x00', '0', '5', '2']",)
2020-05-31 21:27:08,485 [concord.py:send_message()] - WARNING - Resending message, attempt 2: '020204'
2020-05-31 21:27:10,408 [concord.py:send_message()] - WARNING - Resending message, attempt 3: '020204'
2020-05-31 21:27:11,966 [concord.py:maybe_resend_message()] - ERROR - Unable to send message (timeout), too many attempts (3): '020204'
2020-05-31 21:27:13,203 [concord.py:send_message()] - WARNING - Resending message, attempt 2: '022022'
2020-05-31 21:27:15,447 [concord.py:send_message()] - WARNING - Resending message, attempt 3: '022022'
2020-05-31 21:27:16,585 [concord.py:maybe_resend_message()] - ERROR - Unable to send message (timeout), too many attempts (3): '022022'
2020-05-31 21:27:16,648 [concord.py:message_loop()] - ERROR - BadEncoding("Invalid message encoding: ['0', '3', '2', '\\x00', '2', '0', '5', '2']",)
2020-05-31 21:27:21,184 [concord.py:message_loop()] - ERROR - BadEncoding("Invalid message encoding: ['0', '3', '\\x00', '2', '2', '0', '5', '2']",)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "concordsvr.py", line 771, in run
    self.panel.message_loop()
  File "/home/pi/device-concord4/concordsvr/concord/concord.py", line 390, in message_loop
    msg = self.serial_interface.read_next_message()
  File "/home/pi/device-concord4/concordsvr/concord/concord.py", line 150, in read_next_message
    (len_bytes[0], len_bytes[1]))
TypeError: %x format: a number is required, not str

**Comment by automaton82** [comment]
> I have not run through the steps in a long time. I'm waiting to revamp this whole project into the new smart things app when it seems there is good porting documentation.

As an FYI the Classic app is being sunsetted on October 14th and there's currently no custom UI allowed for DTHs. There's a basic API available but it isn't able to do the things required for alarm DTHs like we have here.

As such I've begun the process to move to Home Assistant instead, and with that I ported your web-server code to MQTT as HA (and others) work well with this. I haven't fully tested it yet, but I made a new repository with it working with basic cases here:

https://github.com/automaton82/MQTT-concord4

It's an unfortunate situation with SmartThings.

**Comment by csdozier** [comment]
Thanks for letting me know of the fork. I've thought about moving the Home
Assistant as well.   I havent looked at developing apps on the new app for
a few months, but we I did look at it, it didnt seem like it was going to
work for this app.

**Comment by automaton82** [comment]
Sure no problem. I'm setting up HA now so once that's done if I can get the cards to work with MQTT I'll update that repository with any more information / files that might be helpful. At this point it appears it might be a lot less work to make it work with HA than it was for you to make it work with ST, but we shall see.

**Comment by automaton82** [comment]
Update - HA now working and the latest in my fork is now sending messages to HA MQTT, so I can see the door / CO2 etc status without problem. Overall I'd say integrating via MQTT and HA in general is much easier than ST..

**Comment by nafin** [comment]
This has worked very reliably for me for a couple years now. Many thanks!! Although I have been able to reconfigure automations an scenes to work with the limited lock capability in the new ST app, the limits placed by their “improvements” leave much to be desired.

Are you planning on using the smartthings hub for zigbee/zwave interface into HA with direct control of the concord 4 through HA (there are articles on HA that describe how to do this). Or are you recommending jumping ship from ST entirely and adding a zwave radio to your HA harware?

**Comment by automaton82** [comment]
> This has worked very reliably for me for a couple years now. Many thanks!! Although I have been able to reconfigure automations an scenes to work with the limited lock capability in the new ST app, the limits placed by their “improvements” leave much to be desired.
> 
> Are you planning on using the smartthings hub for zigbee/zwave interface into HA with direct control of the concord 4 through HA (there are articles on HA that describe how to do this). Or are you recommending jumping ship from ST entirely and adding a zwave radio to your HA harware?

I left ST entirely. I bought a Pi4 and a Z-Wave stick. If you want to know how to control concord4 through HA you can use my github repository - https://github.com/automaton82/MQTT-concord4

It's a lot easier to setup in HA and it now works for me successfully (been using for a couple days now). It uses MQTT instead of REST, so HA itself only needs to enable MQTT. After that you just add entities for each zone, and the built-in alarm panel. That repository has the related .yaml changes. If you have trouble setting it up open an issue on that repository and I can try to help.

**Comment by marbaugh** [comment]
> > This has worked very reliably for me for a couple years now. Many thanks!! Although I have been able to reconfigure automations an scenes to work with the limited lock capability in the new ST app, the limits placed by their “improvements” leave much to be desired.
> > Are you planning on using the smartthings hub for zigbee/zwave interface into HA with direct control of the concord 4 through HA (there are articles on HA that describe how to do this). Or are you recommending jumping ship from ST entirely and adding a zwave radio to your HA harware?
> 
> I left ST entirely. I bought a Pi4 and a Z-Wave stick. If you want to know how to control concord4 through HA you can use my github repository - https://github.com/automaton82/MQTT-concord4
> 
> It's a lot easier to setup in HA and it now works for me successfully (been using for a couple days now). It uses MQTT instead of REST, so HA itself only needs [to enable MQTT](https://www.home-assistant.io/integrations/mqtt/). After that you just add entities for each zone, and [the built-in alarm panel](https://www.home-assistant.io/integrations/alarm_control_panel.mqtt/). That repository has the related .yaml changes. If you have trouble setting it up open an issue on that repository and I can try to help.

@automaton82 I have been using SmartThings for year with this concord4 integration.  I have played with HomeAssistant a bit, do you use the mobile app (iOS/Android)? Also how do you access it remotely?  I enjoyed how the SmartThings classic app 'just worked' but know the HomeAssistant takes a bit more setup with HTTPS and port portforwarding.  Just wanted to get your thoughts.

**Comment by automaton82** [comment]
> @automaton82 I have been using SmartThings for year with this concord4 integration. I have played with HomeAssistant a bit, do you use the mobile app (iOS/Android)? Also how do you access it remotely? I enjoyed how the SmartThings classic app 'just worked' but know the HomeAssistant takes a bit more setup with HTTPS and port portforwarding. Just wanted to get your thoughts.

Yes I use the mobile app on both iOS and Android. I access it remotely by first VPNing in to my home. I did not port forward nor setup HTTPS.

If setting up a VPN seems like too much work, they do offer a $5/mo subscription service that re-hosts your HA deployment in the cloud so you can access it anywhere without setting anything up, just like ST.

I've been using HA for a few weeks now after years of ST, and so far I like HA better.
